---
- task:
    metadata:
      name: "GTests"
      decription: "GTests"

    payload:
      command:
        - "/bin/bash"
        - "-c"
        - "bin/checkout.sh && nss/automation/taskcluster/scripts/run_tests.sh"
      env:
        NSS_TESTS: "ssl_gtests gtests"

    extra:
      treeherder:
        symbol: GTest
